# Generated by Django 3.2.3 on 2021-06-10 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image_content',
        ),
    ]
